import Header from "@/components/Header";
import Nab from "@/components/Nab";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className=" dark ">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-row">
          <nav className="hidden lg:flex">
            <Nab />
          </nav>

          <main className="p-2 lg:ml-[300px] w-full">
            <Header />
            <div className="">{children}</div>
          </main>
        </div>
      </body>
    </html>
  );
}
